# Generated by Django 3.2.7 on 2021-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_result'),
        ('account', '0002_customuser_count_num'),
    ]

    operations = [
    ]
