# Generated by Django 3.2.7 on 2021-09-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='count_num',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='result',
            field=models.CharField(choices=[('fire', 'FIRE족'), ('yolo', 'YOLO족'), ('null', '미선택')], default='null', max_length=5),
        ),
    ]
