# Generated by Django 3.2.7 on 2021-09-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_result'),
        ('account', '0006_auto_20210925_0157'),
    ]

    operations = [
    ]
