# Generated by Django 3.2.7 on 2021-09-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210925_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(help_text='닉네임 입력하세요', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, help_text='이미지 입력하세요', null=True, upload_to=''),
        ),
    ]
