# Generated by Django 3.2.7 on 2021-09-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatecomment',
            name='debate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='community.debate'),
            preserve_default=False,
        ),
    ]
